[package]
name = "yoga"
description = "Rust bindings for Facebook's Yoga, a Flexbox layout engine"
license = "MIT"
repository = "https://github.com/bschwind/yoga-rs"
version = "0.1.1"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
# build = "build.rs"

[build-dependencies]
bindgen = "0.23.0"
gcc = "0.3"

[dependencies]
ordered-float = "0.5.0"
